allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  better-sqlite3: false
  esbuild: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - unrs-cli

packages:
  - '.'

overrides:
  glob: '^13.0.6'
  inflight: 'npm:lru-cache@^11.5.2'
  sourcemap-codec: 'npm:@jridgewell/sourcemap-codec@^1.5.5'
minimumReleaseAgeExclude:
  - '@next/env@16.3.8'
  - '@next/eslint-plugin-next@16.3.8'
  - '@next/swc-darwin-arm64@16.3.8'
  - '@next/swc-darwin-x64@16.3.8'
  - '@next/swc-linux-arm64-gnu@16.3.8'
  - '@next/swc-linux-arm64-musl@16.3.8'
  - '@next/swc-linux-x64-gnu@16.3.8'
  - '@next/swc-linux-x64-musl@16.3.8'
  - '@next/swc-win32-arm64-msvc@16.3.8'
  - '@next/swc-win32-x64-msvc@16.3.8'
  - eslint-config-next@16.3.8
  - next@16.3.8
