import type { DayStatus } from '@/types/training/workout.types'

export type ManualRealizedTrainingStatus = Extract<DayStatus, 'completed' | 'partial' | 'missed'>

export type RealizedTrainingCaptureMetric =
  | {
      readonly state: 'known'
      readonly value: number
    }
  | {
      readonly state: 'unknown'
    }

export interface RealizedTrainingCaptureMetrics {
  readonly distanceKm: RealizedTrainingCaptureMetric
  readonly durationMin: RealizedTrainingCaptureMetric
  readonly elevationGainM: RealizedTrainingCaptureMetric
  readonly avgHrBpm: RealizedTrainingCaptureMetric
  readonly rpe: RealizedTrainingCaptureMetric
}

/**
 * Authoritative input for manual realized-training capture.
 *
 * Security/provenance fields that can be derived on the server are deliberately
 * excluded: teamId comes from the athlete scope, source is always `manual`,
 * sourceActivityId is null, and loggedAt is generated by the persistence layer.
 *
 * sessionId is nullable by design: a free/unplanned workout is valid evidence.
 */
export interface ManualRealizedTrainingCaptureInput {
  readonly athleteId: string
  readonly sessionId: string | null
  readonly workoutId: string | null
  readonly date: string
  readonly status: ManualRealizedTrainingStatus
  readonly metrics: RealizedTrainingCaptureMetrics
  readonly feeling: string | null
  readonly athleteNotes: string | null
}

export type RealizedTrainingCaptureField =
  | 'athleteId'
  | 'date'
  | 'status'
  | 'distanceKm'
  | 'durationMin'
  | 'elevationGainM'
  | 'avgHrBpm'
  | 'rpe'

export interface RealizedTrainingCaptureValidationIssue {
  readonly field: RealizedTrainingCaptureField
  readonly code:
    | 'required'
    | 'invalid_date'
    | 'invalid_number'
    | 'out_of_range'
}

export type RealizedTrainingCaptureValidationResult =
  | {
      readonly ok: true
      readonly value: ManualRealizedTrainingCaptureInput
    }
  | {
      readonly ok: false
      readonly issues: readonly RealizedTrainingCaptureValidationIssue[]
    }
