// app/[locale]/layout.tsx
import type { Metadata } from 'next'
import { Geist, Geist_Mono, Barlow_Condensed, DM_Sans, Outfit } from 'next/font/google'
import { notFound } from 'next/navigation'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages, setRequestLocale } from 'next-intl/server'
import { routing, type Locale } from '@/i18n/routing'
import '../globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const barlow = Barlow_Condensed({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800', '900'],
  variable: '--font-barlow',
})

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-dm-sans',
})

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-outfit',
})

export const metadata: Metadata = {
  title: 'El Parque Team App',
  description: 'Generated by m415x',
}

// Genera las rutas estáticas para cada idioma soportado
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: Locale }>
}) {
  const { locale } = await params

  // Si el locale en la URL no existe en routing.locales, devuelve 404
  if (!routing.locales.includes(locale as Locale)) {
    notFound()
  }

  // Habilita el renderizado estático para este locale
  setRequestLocale(locale)

  // Carga los mensajes del idioma actual
  const messages = await getMessages()

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} ${barlow.variable} ${dmSans.variable} ${outfit.variable} h-full antialiased`}
    >
      <body className='font-body bg-background text-foreground antialiased'>
        <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
      </body>
    </html>
  )
}
